### ISSUE TITLE
Footer design broken on Safari on Mac.

### ISSUE THREAD

**Issue by blumenkraft** [Empty2k12/TXWatch#1]
<img width="1131" alt="screenshot 2016-07-17 07 35 41" src="https://cloud.githubusercontent.com/assets/4653850/16898952/206ac27e-4bf1-11e6-99e8-d4935c661f87.png">

**Comment by Empty2k12** [comment]
Thank you for reporting this issue! I will be looking into it ASAP!

**Comment by blumenkraft** [comment]
Looks great now. Thank you.
